force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Simple_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Simple_Sales_Order__c</fullName>
    <label>Simple Sales Order</label>
    <referenceTo>Simple_Sales_Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item_Price_Adjustment__c/Order_Item_Price_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Order Item Price Adjustment</label>
    <nameField>
        <displayFormat>Adjustment-{0}</displayFormat>
        <label>Order Item Price Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Item Price Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item_Price_Adjustment__c/fields/New_Price__c.field-meta.xml
<CustomField>
    <fullName>New_Price__c</fullName>
    <label>New Price</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item_Price_Adjustment__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <label>Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Order Item Price Adjustments</relationshipLabel>
    <relationshipName>Order_Item_Price_Adjustments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item_Price_Adjustment__c/fields/Original_Price__c.field-meta.xml
<CustomField>
    <fullName>Original_Price__c</fullName>
    <label>Original Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Simple_Customer__c/Simple_Customer__c.object-meta.xml
<CustomObject>
    <label>Simple Customer</label>
    <nameField>
        <label>Simple Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simple Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Simple_Customer__c/fields/Stripe_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Account_ID__c</fullName>
    <label>Stripe Account ID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Simple_Sales_Order__c/Simple_Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Simple Sales Order</label>
    <nameField>
        <displayFormat>Order-{000000000}</displayFormat>
        <label>Simple Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simple Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Simple_Sales_Order__c/fields/Simple_Customer__c.field-meta.xml
<CustomField>
    <fullName>Simple_Customer__c</fullName>
    <label>Simple Customer</label>
    <referenceTo>Simple_Customer__c</referenceTo>
    <relationshipLabel>Simple Sales Orders</relationshipLabel>
    <relationshipName>Simple_Sales_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/performPriceMatch.cls
// NON-BULKIFIED FOR READABILITY

global with sharing class performPriceMatch {
    @InvocableMethod(label='Perform a Price Match' )
    public static List<String> performPriceMatch(List<String> adjustmentRecordIDs) {
        List<String> priceMatchOutcomes = new List<String>();

        String recordId = adjustmentRecordIds[0];

        String outcome = '';

        if (qualifiesForInstantReimbursement(recordId)){
            Order_Item_Price_Adjustment__c currentAdjustment = [SELECT Id, Approved__c, Original_Price__c, New_Price__c, Order_Item__r.Id FROM Order_Item_Price_Adjustment__c  WHERE Id = :recordId];
            Order_Item__c currentOrderItem = [Select Id, Name, Price__c, Quantity__c, Simple_Sales_Order__r.Id FROM Order_Item__c WHERE Id = :currentAdjustment.Order_Item__r.Id];
            Simple_Sales_Order__c currentOrder = [Select Id, Simple_Customer__r.Stripe_Account_ID__c FROM Simple_Sales_Order__c WHERE Id= :currentOrderItem.Simple_Sales_Order__r.id];
            currentAdjustment.Approved__c = true;
            currentOrderItem.Price__c = currentAdjustment.New_Price__c;
            Integer adjustmentCreditAmountInCents = (100*(currentOrderItem.Quantity__c * (currentAdjustment.Original_Price__c - currentAdjustment.New_Price__c))).intValue();
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            req.setEndpoint('callout:StripeBasic/transfers');
            String description = 'Price Match: ' + currentOrderItem.Name;
            String body ='amount='+String.ValueOf(adjustmentCreditAmountInCents)+'&description='+description+'&currency=usd&destination='+currentOrder.Simple_Customer__r.Stripe_Account_ID__c;
            req.setBody(body);
            HttpResponse res = http.send(req);
            System.debug(res.getBody());
            update currentAdjustment;
            update currentOrderItem;   
            outcome = 'Instant Reimbursement Approved'; 
        }else{
            outcome = 'Price Match Submitted';

        }


        priceMatchOutcomes.add(outcome);
        return priceMatchOutcomes;
    }

    public static Boolean qualifiesForInstantReimbursement(String adjustmentRecordId){

        return true;

    }

    public static void submitPriceMatchForApproval(String adjustmentRecordId){

    }

} 
        